service: ${file(./config/servicename.json):service}-${opt:stage, 'dev'}
provider:
  name: azure
  location: ${opt:location, 'West US'}
  environment:
    PROVIDER: 'azure'
plugins: 
  - serverless-azure-functions

functions:
  proxy:
    handler: handler.proxy
    events:
      - http: true,
        x-azure-settings:
          authLevel : anonymous
          methods: post
          route: /         
      - http: true,
        x-azure-settings:
          direction: out
          name: res 
package:
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'handler_aws.js'